name: Release

on:
  workflow_dispatch:
  push:
    branches: [testing]
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - '.gitignore'
env:
  node_version: "22.x"
  FORCE_COLOR: 3
concurrency: ${{ github.ref }}
jobs:
  build_and_release:
    name: Build and Release
    timeout-minutes: 90
    runs-on: [openshift-ocp-chem]
    # needs: [test, audit, lint]
    env:
      IMAGE_NAME: quay.byu.edu/chem/mapkinase
    steps:
      - name: Setup git
        run: sudo apt-get update && sudo apt-get install -y git

      - name: Check out
        uses: actions/checkout@v6

      - name: Login to Quay
        id: login-quay
        uses: docker/login-action@v4
        with:
          registry: quay.byu.edu
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v4
        with:
          platforms: linux/amd64

      - name: Build and push the Docker image
        id: build-push-image
        uses: docker/build-push-action@v7
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Notify the manifest repo
        uses: peter-evans/repository-dispatch@v4
        with:
          token: ${{ secrets.K8S_APP_MANIFESTS_TOKEN }}
          repository: byu-oit/k8s-app-manifests
          event-type: app-version-released
          client-payload: '
            {
              "appName":"chem-mapkinase",
              "image":"${{ env.IMAGE_NAME }}@${{ steps.build-push-image.outputs.digest }}",
              "sourceCommitSHA":"${{ github.sha }}",
              "environments": [
                {"name":"dev","autodeploy":true},
                {"name":"prd"}
              ]
            }'

# Note: RFCs will happen when manifest PRs are merged at deploy time. No RFCs are needed here because no environments were deployed.